---
- name: Basic usage
  hosts: reports32
  remote_user: brent
  tasks:
  - name: basic usage
    ansible.builtin.debug:
      msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}' is the HOME environment variable."
  - name: update cache and upgrade apt packages
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
